workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      vars:
        # helps Gradle find the SDK on Codemagic
        ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT
    scripts:
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build debug APK
        script: |
          chmod +x ./gradlew
          ./gradlew --no-daemon clean assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

  android_release:
    name: Android Release APK + AAB (signed)
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      android_signing:
        - keystore_reference   # <-- replace after you upload keystore in step 3
    scripts:
      - name: Set Android SDK location
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build release
        script: |
          chmod +x ./gradlew
          ./gradlew --no-daemon clean assembleRelease bundleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/bundle/release/*.aab
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
